# -*- coding: utf-8 -*-
"""Zomato data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14cW1D7TbtmtloNIPEWEonx3bFK2H4uOa

#import necessart python libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""#Create the data frame

"""

dataframe =pd.read_csv("/content/Zomato data .csv")
print(dataframe.head())

dataframe

"""Convert the data type of colum rate"""

def handleRate(value):
  value=str(value).split('/')
  value=value[0]
  return float(value)
dataframe['rate']=dataframe['rate'].apply(handleRate)
print(dataframe.head())

dataframe.info()

"""#Resturant Types

"""

dataframe.head()

sns.countplot(x=dataframe['listed_in(type)'])
plt.xlabel ('Types of Reaturant')

"""Majority of the restaurant fall in dinning category

"""

dataframe.head()

grouped_data = dataframe.groupby('listed_in(type)')['votes'].sum()
result = pd.DataFrame({'votes':grouped_data})
plt.plot(result,c='blue',marker='o')
plt.xlabel('Type of Restaurant',c='black',size='20')
plt.ylabel('Votes',c='black',size='20')

dataframe.head()

"""Dining resturants has resived maximum votes"""

plt.hist(dataframe['rate'],bins=5)
plt.title('ratings distribution')
plt.show()

"""Average order spending by couples"""

couple_data=dataframe['approx_cost(for two people)']
sns.countplot(x=couple_data)
plt.xlabel('Order by the Couples')

dataframe.head()

"""Which mode receives maximum rating"""

plt.figure(figsize =(6,6))
sns.boxplot(x='online_order',y='rate',data=dataframe)

dataframe.head( )

"""offline order received lower rating in comparison to online order"""

pivot_table= dataframe.pivot_table(index='listed_in(type)',columns='online_order',aggfunc='size',fill_value=0)
sns.heatmap(pivot_table,annot=True,cmap='YlGnBu',fmt='d')
plt.title('heatmap')
plt.xlabel('online_order')
plt.ylabel('listed in(type)')
plt.show()

"""**Conclusion:** Dining restaurants primarily accept offline orders whereas cafes primarily receive online orders.This suggests that clients Prefers order in person at restaurant, but prefers online ordering as cafes."""